# Generated by Django 5.2.5 on 2025-09-02 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ttl', models.PositiveIntegerField(default=0)),
                ('forcedBitrate', models.PositiveIntegerField(default=0)),
                ('annotate', models.CharField(max_length=128)),
                ('nocdn', models.PositiveIntegerField(default=0)),
                ('whitelisthref', models.CharField(max_length=128)),
                ('ipGeoRules', models.CharField(max_length=128)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.video')),
            ],
        ),
    ]
