# Generated by Django 5.2.5 on 2025-09-02 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_otp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
        migrations.RenameField(
            model_name='mobileresolution',
            old_name='resolution',
            new_name='value',
        ),
    ]
